// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20170215.54ef86fe 2017-02-15T10:25:45Z

#ifndef ccnxPortalClient_About_h
#define ccnxPortalClient_About_h
/**
 * Embedded string containing information for the what(1) command.
 *
 */
extern const char *ccnxPortalClient_What;

/**
 * Return the name as a C string.
 *
 * @return The name as a C string.
 */
const char *ccnxPortalClientAbout_Name(void);

/**
 * Return the version as a C string.
 *
 * @return The version as a C string.
 */
const char *ccnxPortalClientAbout_Version(void);

/**
 * Return the About text as a C string.
 *
 * @return The About text as a C string.
 */
const char *ccnxPortalClientAbout_About(void);

/**
 * Return the minimum copyright notice as a C string.
 *
 * @return The minimum copyright notice as a C string.
 */
const char *ccnxPortalClientAbout_MiniNotice(void);

/**
 * Return the short copyright notice as a C string.
 *
 * @return The short copyright notice as a C string.
 */
const char *ccnxPortalClientAbout_ShortNotice(void);

/**
 * Return the long copyright notice as a C string.
 *
 * @return The long copyright notice as a C string.
 */
const char *ccnxPortalClientAbout_LongNotice(void);

#endif // ccnxPortalClient_About_h
