// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20170215.54ef86fe 2017-02-15T09:29:05Z

#ifndef ccnxNotifyAPI_About_h
#define ccnxNotifyAPI_About_h
/**
 * Embedded string containing information for the what(1) command.
 *
 */
extern const char *ccnxNotifyAPI_What;

/**
 * Return the name as a C string.
 *
 * @return The name as a C string.
 */
const char *ccnxNotifyAPIAbout_Name(void);

/**
 * Return the version as a C string.
 *
 * @return The version as a C string.
 */
const char *ccnxNotifyAPIAbout_Version(void);

/**
 * Return the About text as a C string.
 *
 * @return The About text as a C string.
 */
const char *ccnxNotifyAPIAbout_About(void);

/**
 * Return the minimum copyright notice as a C string.
 *
 * @return The minimum copyright notice as a C string.
 */
const char *ccnxNotifyAPIAbout_MiniNotice(void);

/**
 * Return the short copyright notice as a C string.
 *
 * @return The short copyright notice as a C string.
 */
const char *ccnxNotifyAPIAbout_ShortNotice(void);

/**
 * Return the long copyright notice as a C string.
 *
 * @return The long copyright notice as a C string.
 */
const char *ccnxNotifyAPIAbout_LongNotice(void);

#endif // ccnxNotifyAPI_About_h
