// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20170214.46e2c73a 2017-02-14T20:35:31Z

#ifndef longBowReportANSITerminal_About_h
#define longBowReportANSITerminal_About_h
/**
 * Embedded string containing information for the what(1) command.
 *
 */
extern const char *longBowReportANSITerminal_What;

/**
 * Return the name as a C string.
 *
 * @return The name as a C string.
 */
const char *longBowReportANSITerminalAbout_Name(void);

/**
 * Return the version as a C string.
 *
 * @return The version as a C string.
 */
const char *longBowReportANSITerminalAbout_Version(void);

/**
 * Return the About text as a C string.
 *
 * @return The About text as a C string.
 */
const char *longBowReportANSITerminalAbout_About(void);

/**
 * Return the minimum copyright notice as a C string.
 *
 * @return The minimum copyright notice as a C string.
 */
const char *longBowReportANSITerminalAbout_MiniNotice(void);

/**
 * Return the short copyright notice as a C string.
 *
 * @return The short copyright notice as a C string.
 */
const char *longBowReportANSITerminalAbout_ShortNotice(void);

/**
 * Return the long copyright notice as a C string.
 *
 * @return The long copyright notice as a C string.
 */
const char *longBowReportANSITerminalAbout_LongNotice(void);

#endif // longBowReportANSITerminal_About_h
