// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20170206.46e2c73a 2017-02-06T08:50:09Z

#include "parcPublicKey_About.h"

const char *parcPublicKey_What = "@(#)" "PARC public key " RELEASE_VERSION " 2017-02-15T13:31:10.603139"
                                 "@(#)" "\tCopyright (c) 2017 Cisco and/or its affiliates.";

const char *
parcPublicKeyAbout_Name(void)
{
    return "PARC public key";
}

const char *
parcPublicKeyAbout_Version(void)
{
    return RELEASE_VERSION;
}

const char *
parcPublicKeyAbout_About(void)
{
    return "PARC public key "RELEASE_VERSION " 2017-02-15T13:31:10.603139" "\nCopyright (c) 2017 Cisco and/or its affiliates.\n";
}

const char *
parcPublicKeyAbout_MiniNotice(void)
{
    return "Copyright (c) 2017 Cisco and/or its affiliates.\n";
}

const char *
parcPublicKeyAbout_ShortNotice(void)
{
    return "Copyright (c) 2017 Cisco and/or its affiliates.\n";
}

const char *
parcPublicKeyAbout_LongNotice(void)
{
    return "Copyright (c) 2017 Cisco and/or its affiliates.\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at:\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n";
}

