// DO NOT EDIT THIS FILE.  IT IS AUTOMATICALLY GENERATED.
// longbow-generate-about 1.0.20170215.54ef86fe 2017-02-15T09:29:05Z

#include "librta_About.h"

const char *librta_What = "@(#)" "librta " RELEASE_VERSION " 2017-02-20T14:19:07.130301"
                          "@(#)" "\tCopyright (c) 2017 Cisco and/or its affiliates.";

const char *
librtaAbout_Name(void)
{
    return "librta";
}

const char *
librtaAbout_Version(void)
{
    return RELEASE_VERSION;
}

const char *
librtaAbout_About(void)
{
    return "librta "RELEASE_VERSION " 2017-02-20T14:19:07.130301" "\nCopyright (c) 2017 Cisco and/or its affiliates.\n";
}

const char *
librtaAbout_MiniNotice(void)
{
    return "Copyright (c) 2017 Cisco and/or its affiliates.\n";
}

const char *
librtaAbout_ShortNotice(void)
{
    return "Copyright (c) 2017 Cisco and/or its affiliates.\n";
}

const char *
librtaAbout_LongNotice(void)
{
    return "Copyright (c) 2017 Cisco and/or its affiliates.\nLicensed under the Apache License, Version 2.0 (the \"License\");\nyou may not use this file except in compliance with the License.\nYou may obtain a copy of the License at:\n\n    http://www.apache.org/licenses/LICENSE-2.0\n\nUnless required by applicable law or agreed to in writing, software\ndistributed under the License is distributed on an \"AS IS\" BASIS,\nWITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\nSee the License for the specific language governing permissions and\nlimitations under the License.\n";
}

